-- Title: Create Death Date schema for CRS project
-- Author: David Sharpe
-- Date: 29-Sept-2017

SPOOL schema_death_date_audit.log;

DROP USER ESB_DEATH CASCADE;

-- NOTE: confirm password
CREATE USER ESB_DEATH
  IDENTIFIED BY ***
  DEFAULT TABLESPACE ESB_DEATH_REG_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

  -- 2 Roles for ESB_DEATH 
  GRANT CONNECT TO ESB_DEATH;
  GRANT RESOURCE TO ESB_DEATH;
  ALTER USER ESB_DEATH DEFAULT ROLE ALL;

  -- 8 System Privileges for ESB_DEATH 
  GRANT ALTER SESSION TO ESB_DEATH;
  GRANT CREATE CLUSTER TO ESB_DEATH;
  GRANT CREATE DATABASE LINK TO ESB_DEATH;
  GRANT CREATE SEQUENCE TO ESB_DEATH;
  GRANT CREATE SYNONYM TO ESB_DEATH;
  GRANT CREATE TABLE TO ESB_DEATH;
  GRANT CREATE VIEW TO ESB_DEATH;
  GRANT UNLIMITED TABLESPACE TO ESB_DEATH;

  -- 2 Tablespace Quotas for ESB_DEATH 
  ALTER USER ESB_DEATH QUOTA UNLIMITED ON ESB_DEATH_REG_DATA;
  ALTER USER ESB_DEATH QUOTA UNLIMITED ON ESB_DEATH_REG_INDEX;

SPOOL OFF
