-- Title: Create Death Date tablespace for CRS project
-- Author: Clarisse Baudot
-- Date: 05-Oct-2017
--
-- (Original filename CreTbs_ESB_DEATH.sql)
--
-- Change file paths and values where necessary.

spool CreTbs_ESB_DEATH
CREATE TABLESPACE ESB_DEATH_REG_DATA DATAFILE 
  '/u01/oracle/oradata/esbhd1/esb_death_reg_data01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 200M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ESB_DEATH_REG_INDEX DATAFILE 
  '/u01/oracle/oradata/esbhd1/esb_death_reg_index01.dbf' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 200M
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
spool off
