name: Dev-Workflow
on:
   workflow_dispatch:
     inputs:
        environment:
         description: 'Environment to run tests against' 
         type: environment 
         required: true
        version:
         description: 'Version Number'
         required: false
#   push: 
#     branches:
#       - main
#   pull_request:
  
concurrency: dev

env:
#  APP_IMAGE: ${{ secrets.APP_IMAGE }} 
  IMAGE_ID: ${{ secrets.AWS_ECR_URI_DEV }}
  IMAGE_NAME: hcimdddev
  TF_VERSION: 1.2.2
  TG_VERSION: 0.37.1
  TG_SRC_PATH: Terraform
  TFC_WORKSPACE: dev
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  docker_push:
    name: docker push
    environment:  dev
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN }}
          aws-region: ca-central-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: ${{ env.IMAGE_ID  }}:latest
          build-args: |
            FTP_PRIVATE_KEY=${{ secrets.FTP_PRIVATE_KEY }}
            SSL_KEY=${{ secrets.SSL_KEY }}
            SSL_TRUST=${{ secrets.SSL_TRUST }}
          
  terraform_apply:
    name: terraform apply 
    environment: dev
    runs-on: ubuntu-22.04
    needs: docker_push
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TERRAFORM_DEPLOY_ROLE_ARN }}
          aws-region: ca-central-1
          
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          
      - uses: autero1/action-terragrunt@v1.3.1
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
            
      - name: Terragrunt Apply
        working-directory: ${{ env.TG_SRC_PATH }}/${{env.TFC_WORKSPACE }}
        env:
          app_image: ${{ env.IMAGE_ID }}:${{ github.sha }}
          LICENSE_PLATE: ${{ secrets.MY_LICENSE_PLATE }}
        run: |
            echo "repository variable : '${{ vars.ENVIRONMENT }}' " 
            echo "Environment variable: '${{ github.event.inputs.environment }}' " 
            terragrunt run-all apply --terragrunt-non-interactive
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Scan the webapplication
    needs: terraform_apply
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://hcim-death-date-esb.<license plate>-dev.nimbus.cloud.gov.bc.ca/'
